#!/usr/bin/env python3
"""Regenerate COVERAGE.md from the tests' @pytest.mark.ledger markers and the ledger file.

    verification/stage-1/.venv/Scripts/python.exe verification/stage-1/gen_coverage.py
"""
import json
import pathlib
import re
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
LEDGER = HERE.parent.parent / "evidence" / "ledger" / "ledger.md"

# Ledger items no black-box HTTP test in this suite can check, with the reason.
NOT_COVERED = {
    "S1-002": "partly: candidate.py runs the image alone with -e PORT and a port mapping (no compose); "
              "'no outbound network at run time' is not observable here; Gate's isolated WSL harness run covers it",
    "S1-003": "test_port_env_and_default_port needs candidate.py (main PORT=9137, second container PORT unset on 8080)",
    "S1-005": "partly: candidate.py applies --cpus 2 --memory 2g; 50 in flight with a 5 s cap is asserted; "
              "memory headroom is not measured",
    "S1-036": "partly: export must not contain plaintext passwords; the hashing algorithm is a code audit (Gate)",
    "A-13": "partly: verbatim seeded references/ids are checked; the default created_at (reset time) is not",
    "A-14": "covered: unknown routes must be 404; wrong method accepts 404 or 405",
    "A-16": "2.5 -> 422 is checked; 4.0 is implementation-defined (ledger) and deliberately not tested",
    "A-17": "a stage-2 behaviour probe needs stage-2 requirements; Gate's harness run checks the 'claimed stage' line",
    "A-18": "procedural (evidence source), not a product behaviour",
    "A-19": "fixture ids over 64 characters are not tested (ledger: not tested by the band)",
    "A-09": "tie order for equal starts_at is unspecified; any deterministic order accepted, not tested",
}


def main():
    with tempfile.TemporaryDirectory() as td:
        dump = pathlib.Path(td) / "ledger.json"
        subprocess.run([sys.executable, "-m", "pytest", str(HERE), "--collect-only", "-q",
                        "--dump-ledger", str(dump)], cwd=str(HERE), check=True, capture_output=True)
        mapping = json.loads(dump.read_text(encoding="utf-8"))
    by_id = {}
    for test, ids in mapping.items():
        base = test.split("[")[0]
        for i in ids:
            by_id.setdefault(i, [])
            if base not in by_id[i]:
                by_id[i].append(base)
    text = LEDGER.read_text(encoding="utf-8").split("\n## Stage 2")[0]  # stage-1 section only
    items = []
    for m in re.finditer(r"^- (S1-\d{3}) \[[^\]]*\] (.*)$", text, re.M):
        items.append((m.group(1), m.group(2)))
    for m in re.finditer(r"^- (A-\d{2}) \*\*(.*?)\*\*", text, re.M):
        items.append((m.group(1), m.group(2)))
    lines = ["# Stage-1 verifier suite: ledger coverage", "",
             "Generated by `gen_coverage.py` from the `@pytest.mark.ledger` markers and "
             "`evidence/ledger/ledger.md`. Test names are `file::test` (parametrized cases collapsed).", "",
             f"Collected test cases: {len(mapping)}.", "",
             "| Ledger item | Requirement (abridged) | Tests | Note |", "|---|---|---|---|"]
    uncovered = []
    for iid, desc in items:
        short = desc.replace("|", "\\|")
        short = short if len(short) <= 110 else short[:107] + "..."
        tests = by_id.get(iid, [])
        note = NOT_COVERED.get(iid, "")
        if not tests and not note:
            uncovered.append(iid)
            note = "NOT COVERED"
        cell = "<br>".join(f"`{t}`" for t in tests) if tests else "—"
        lines.append(f"| {iid} | {short} | {cell} | {note} |")
    unknown = sorted(set(by_id) - {i for i, _ in items})
    lines += ["", f"Uncovered without a reason: {', '.join(uncovered) if uncovered else 'none'}.",
              f"Marker ids not in the ledger: {', '.join(unknown) if unknown else 'none'}.", ""]
    (HERE / "COVERAGE.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(items)} ledger items, {len(mapping)} test cases, uncovered: {uncovered}, unknown: {unknown}")


if __name__ == "__main__":
    main()
